CREATE SEQUENCE cuentas_numero_seq START WITH 100000000000000 INCREMENT BY 1;

CREATE TABLE domicilios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR(100) NOT NULL,
    numero_exterior VARCHAR(15) NOT NULL,
    numero_interior VARCHAR(15),
    colonia VARCHAR(80) NOT NULL,
    municipio VARCHAR(80) NOT NULL,
    estado VARCHAR(80) NOT NULL,
    codigo_postal CHAR(5) NOT NULL CHECK (codigo_postal ~ '^[0-9]{5}$'),
    pais VARCHAR(60) NOT NULL
);

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    segundo_nombre VARCHAR(50),
    apellido_paterno VARCHAR(50) NOT NULL,
    apellido_materno VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    curp VARCHAR(18) NOT NULL UNIQUE CHECK (curp ~ '^[A-Z][AEIOUX][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])[MH](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[A-Z0-9][0-9]$'),
    rfc VARCHAR(13) NOT NULL UNIQUE CHECK (rfc ~ '^[A-ZÑ&]{3,4}[0-9]{6}[A-Z0-9]{3}$'),
    sexo CHAR(1) NOT NULL CHECK (sexo IN ('M', 'H', 'X')),
    nacionalidad VARCHAR(60) NOT NULL,
    estado_civil VARCHAR(20) NOT NULL CHECK (estado_civil IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO', 'UNION_LIBRE')),
    correo_electronico VARCHAR(100) NOT NULL,
    telefono_movil CHAR(10) NOT NULL CHECK (telefono_movil ~ '^[0-9]{10}$'),
    telefono_alternativo CHAR(10) CHECK (telefono_alternativo IS NULL OR telefono_alternativo ~ '^[0-9]{10}$'),
    ocupacion VARCHAR(80) NOT NULL,
    empresa VARCHAR(100) NOT NULL,
    ingreso_mensual NUMERIC(19, 2) NOT NULL CHECK (ingreso_mensual > 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domicilio_id BIGINT NOT NULL UNIQUE REFERENCES domicilios(id) ON DELETE RESTRICT,
    CHECK (fecha_nacimiento <= CURRENT_DATE - INTERVAL '18 years')
);

CREATE UNIQUE INDEX uq_clientes_correo_lower ON clientes (LOWER(correo_electronico));
CREATE INDEX idx_clientes_activos ON clientes (activo);
CREATE INDEX idx_clientes_fecha_registro ON clientes (fecha_registro);

CREATE TABLE cuentas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta VARCHAR(16) NOT NULL UNIQUE DEFAULT ('4' || LPAD(NEXTVAL('cuentas_numero_seq')::TEXT, 15, '0')),
    cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE RESTRICT,
    saldo NUMERIC(19, 2) NOT NULL DEFAULT 0.00 CHECK (saldo >= 0),
    estatus VARCHAR(10) NOT NULL DEFAULT 'ACTIVA' CHECK (estatus IN ('ACTIVA', 'INACTIVA')),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cuentas_cliente ON cuentas (cliente_id);
CREATE INDEX idx_cuentas_activas ON cuentas (estatus) WHERE estatus = 'ACTIVA';