CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_correo_lower ON usuarios (LOWER(correo));

CREATE TABLE IF NOT EXISTS sesiones_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    correo VARCHAR(100) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    fecha_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_actividad TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_sesiones_token ON sesiones_usuario (token);
CREATE INDEX IF NOT EXISTS idx_sesiones_activa_expiracion ON sesiones_usuario (activa, fecha_expiracion);

INSERT INTO usuarios (correo, password, nombre, activo)
VALUES ('admin@banco.com', 'Admin123!', 'Administrador Sistema', TRUE)
ON CONFLICT (correo) DO NOTHING;

INSERT INTO usuarios (correo, password, nombre, activo)
VALUES ('juan.perez@example.com', 'Clave123!', 'Juan Carlos Perez', TRUE)
ON CONFLICT (correo) DO NOTHING;
