CREATE TABLE biometria_clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL UNIQUE REFERENCES clientes(id) ON DELETE RESTRICT,
    tipo_biometria VARCHAR(50) NOT NULL DEFAULT 'FACIAL_MEDIAPIPE',
    embedding TEXT NOT NULL,
    confianza_deteccion NUMERIC(5, 2) NOT NULL CHECK (confianza_deteccion >= 0 AND confianza_deteccion <= 100),
    rostros_detectados INT NOT NULL DEFAULT 1 CHECK (rostros_detectados > 0),
    foto_base64 TEXT,
    fecha_captura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estatus VARCHAR(20) NOT NULL DEFAULT 'VIGENTE' CHECK (estatus IN ('VIGENTE', 'ACTUALIZADA', 'REVOCADA'))
);

CREATE INDEX idx_biometria_cliente ON biometria_clientes (cliente_id);
CREATE INDEX idx_biometria_estatus ON biometria_clientes (estatus);
